apiVersion: v2
name: otterscale-license-operator
version: 1.3.2
appVersion: "1.3.2"
description: >-
  Otterscale license operator chart.
home: https://otterscale.github.io
sources:
  - https://github.com/otterscale/charts
maintainers:
  - name: Chung-Hsuan Tsai
    email: paul_tsai@phison.com
keywords:
  - otterscale
  - license
type: application
annotations:
  module.otterscale.io/depends-on: "otterscale-node-feature-discovery"
