apiVersion: v2
name: otterscale-workload-operator
version: 0.1.0
# renovate: github=otterscale/workload-operator
appVersion: "v0.9.1"
description: >-
  Workload Operator — manages workload resources on Kubernetes.
  Deploys the Workload Operator controller manager.
home: https://github.com/otterscale/workload-operator
icon: https://github.com/otterscale.png
sources:
  - https://github.com/otterscale/charts
maintainers:
  - name: Chung-Hsuan Tsai
    email: paul_tsai@phison.com
keywords:
  - workload
  - operator
  - ai
  - ml
type: application
kubeVersion: ">=1.25.0-0"
annotations:
  module.otterscale.io/namespace: "otterscale-system"
  artifacthub.io/license: Apache-2.0
