apiVersion: v2
name: otterscale-cert-manager
version: 0.1.0
# renovate: helm=cert-manager registry=https://charts.jetstack.io
appVersion: "v1.20.1"
description: >-
  cert-manager — Kubernetes certificate management controller.
  Wrapper chart for Jetstack cert-manager.
home: https://cert-manager.io
icon: https://cert-manager.io/images/cert-manager-logo-icon.svg
sources:
  - https://github.com/otterscale/charts
  - https://github.com/cert-manager/cert-manager
maintainers:
  - name: Chung-Hsuan Tsai
    email: paul_tsai@phison.com
keywords:
  - cert-manager
  - certificates
  - tls
  - security
type: application
kubeVersion: ">=1.25.0-0"
dependencies:
  - name: cert-manager
    version: v1.20.1
    repository: https://charts.jetstack.io
annotations:
  module.otterscale.io/namespace: "cert-manager"
  artifacthub.io/license: Apache-2.0
