gpu-operator:
  cdi:
    enabled: false

  sandboxWorkloads:
    enabled: true

  driver:
    enabled: true
    version: "580.126.20"
    upgradePolicy:
      autoUpgrade: false

  devicePlugin:
    enabled: false

  operator:
    cleanupCRD: true
    upgradeCRD: false

  dcgm:
    enabled: true

  dcgmExporter:
    enabled: true
    serviceMonitor:
      enabled: true

  nodeStatusExporter:
    enabled: true

  vgpuDeviceManager:
    enabled: false
