gpu-operator:
  cdi:
    enabled: false

  sandboxWorkloads:
    enabled: true

  driver:
    enabled: true
    version: "580.159.04"
    upgradePolicy:
      autoUpgrade: false
    usePrecompiled: true
    repository: ghcr.io
    image: otterscale/nvidia-driver

  devicePlugin:
    enabled: false

  operator:
    cleanupCRD: true
    upgradeCRD: false

  dcgm:
    enabled: true

  dcgmExporter:
    enabled: true
    serviceMonitor:
      enabled: true

  nodeStatusExporter:
    enabled: true

  vgpuDeviceManager:
    enabled: false

  migManager:
    enabled: false
  
  toolkit:
    env:
    - name: CONTAINERD_CONFIG
      value: /var/lib/rancher/rke2/agent/etc/containerd/config.toml
    - name: CONTAINERD_SOCKET
      value: /run/k3s/containerd/containerd.sock
    - name: CONTAINERD_RUNTIME_CLASS
      value: nvidia
    - name: CONTAINERD_SET_AS_DEFAULT
      value: "true"
  
