apiVersion: v2
name: otterscale-lincense-operator
version: 1.2.0
appVersion: "1.0.0"
description: >-
  Otterscale lincense operator chart.
home: https://otterscale.github.io
sources:
  - https://github.com/otterscale/charts
maintainers:
  - name: Chung-Hsuan Tsai
    email: paul_tsai@phison.com
keywords:
  - otterscale
  - license
type: application
annotations:
  module.otterscale.io/depends-on: "otterscale-node-feature-discovery"
