apiVersion: v2
name: otterscale-istiod
version: 0.1.0
# renovate: helm=istiod registry=https://istio-release.storage.googleapis.com/charts
appVersion: "1.29.1"
description: >-
  Istiod — Istio control plane / discovery server.
  Requires otterscale-istio-base to be installed first.
home: https://istio.io
icon: https://github.com/istio.png
sources:
  - https://github.com/otterscale/charts
maintainers:
  - name: Chung-Hsuan Tsai
    email: paul_tsai@phison.com
keywords:
  - istio
  - istiod
  - service-mesh
type: application
kubeVersion: ">=1.25.0-0"
annotations:
  module.otterscale.io/depends-on: "otterscale-istio-base"
  module.otterscale.io/namespace: "istio-system"
  artifacthub.io/license: Apache-2.0
dependencies:
  - name: istiod
    version: 1.29.1
    repository: https://istio-release.storage.googleapis.com/charts
