---
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: workload-operator
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: workload-operator-application-admin-role
rules:
- apiGroups:
  - workload.otterscale.io
  resources:
  - applications
  verbs:
  - '*'
- apiGroups:
  - workload.otterscale.io
  resources:
  - applications/status
  verbs:
  - get
apiVersion: rbac.authorization.k8s.io/v1
---
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: workload-operator
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: workload-operator-application-editor-role
rules:
- apiGroups:
  - workload.otterscale.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workload.otterscale.io
  resources:
  - applications/status
  verbs:
  - get
apiVersion: rbac.authorization.k8s.io/v1
---
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: workload-operator
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: workload-operator-application-viewer-role
rules:
- apiGroups:
  - workload.otterscale.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workload.otterscale.io
  resources:
  - applications/status
  verbs:
  - get
apiVersion: rbac.authorization.k8s.io/v1
---
kind: ClusterRole
metadata:
  name: workload-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - workload.otterscale.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workload.otterscale.io
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
apiVersion: rbac.authorization.k8s.io/v1
---
kind: ClusterRole
metadata:
  name: workload-operator-metrics-auth-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
apiVersion: rbac.authorization.k8s.io/v1
---
kind: ClusterRole
metadata:
  name: workload-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
apiVersion: rbac.authorization.k8s.io/v1
---
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: workload-operator
  name: workload-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workload-operator-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "otterscale-workload-operator.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
apiVersion: rbac.authorization.k8s.io/v1
---
kind: ClusterRoleBinding
metadata:
  name: workload-operator-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workload-operator-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: {{ include "otterscale-workload-operator.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
apiVersion: v1
