apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "otterscale-workload-operator.labels" . | nindent 4 }}
  name: workload-operator-controller-manager-metrics-service
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - name: https
    port: {{ .Values.service.metricsPort }}
    protocol: TCP
    targetPort: {{ .Values.service.metricsPort }}
  selector:
    {{- include "otterscale-workload-operator.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
