{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "otterscale-workload-operator.labels" . | nindent 4 }}
  name: {{ include "otterscale-workload-operator.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
{{- end }}
