{{- if .Values.vgChecker.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "otterscale-topolvm.fullname" . }}-vg-checker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale-topolvm.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "otterscale-topolvm.fullname" . }}-vg-checker
  labels:
    {{- include "otterscale-topolvm.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "otterscale-topolvm.fullname" . }}-vg-checker
  labels:
    {{- include "otterscale-topolvm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "otterscale-topolvm.fullname" . }}-vg-checker
subjects:
  - kind: ServiceAccount
    name: {{ include "otterscale-topolvm.fullname" . }}-vg-checker
    namespace: {{ .Release.Namespace }}
{{- end }}
