# No configurable values. Upstream chart is installed as-is.
kyverno:
  admissionController:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 10
  backgroundController:
    replicas: 2
  cleanupController:
    replicas: 2
  reportsController:
    replicas: 2