{{- if and .Values.harbor.enabled .Values.keycloakx.enabled .Values.harbor.oidc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterscale.fullname" . }}-harbor-oidc-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: harbor
type: Opaque
stringData:
  CONFIG_OVERWRITE_JSON: |
    {
      "auth_mode": "oidc_auth",
      "oidc_name": "Keycloak",
      "oidc_endpoint": "{{ include "otterscale.externalURL" . }}/auth/realms/otterscale",
      "oidc_client_id": "{{ .Values.keycloakx.client.id }}",
      "oidc_client_secret": "{{ include "otterscale.keycloakx.clientSecret" . }}",
      "oidc_scope": "{{ .Values.harbor.oidc.scope }}",
      "oidc_auto_onboard": {{ .Values.harbor.oidc.autoOnboard }},
      "oidc_groups_claim": "{{ .Values.harbor.oidc.groupsClaim }}",
      "oidc_admin_group": "{{ .Values.harbor.oidc.adminGroup }}",
      "oidc_verify_cert": false,
      "primary_auth_mode": true
    }
{{- end }}
