{{- if .Values.keycloakx.enabled -}}
{{- $secretName := printf "%s-keycloakx-client-secret" (include "otterscale.fullname" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloakx
type: Opaque
stringData:
  client-secret: {{ include "otterscale.keycloakx.clientSecret" . }}
{{- end }}
