apiVersion: v1
kind: Service
metadata:
  name: {{ include "otterscale.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: NodePort
  selector:
    {{- include "otterscale.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: connectrpc
      port: {{ .Values.otterscaleServer.ports.http }}
      targetPort: http
      nodePort: {{ .Values.otterscaleServer.nodePorts.http }}
      protocol: TCP
    - name: tunnel
      port: {{ .Values.otterscaleServer.ports.tunnel }}
      targetPort: tunnel
      nodePort: {{ .Values.otterscaleServer.nodePorts.tunnel }}
      protocol: TCP
