apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otterscale.server.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  OTTERSCALE_SERVER_ADDRESS: ":{{ .Values.otterscaleServer.ports.http }}"
  OTTERSCALE_SERVER_TUNNEL_ADDRESS: "0.0.0.0:{{ .Values.otterscaleServer.ports.tunnel }}"
  OTTERSCALE_SERVER_KEYCLOAK_REALM_URL: "{{ include "otterscale.externalURL" . }}/auth/realms/otterscale"
  OTTERSCALE_SERVER_KEYCLOAK_CLIENT_ID: {{ .Values.keycloakx.client.id | quote }}
  OTTERSCALE_SERVER_ALLOWED_ORIGINS: "{{ include "otterscale.externalURL" . }}"
  OTTERSCALE_SERVER_EXTERNAL_URL: "{{ include "otterscale.scheme" . }}://{{ .Values.istio.externalIP }}:{{ .Values.otterscaleServer.nodePorts.http }}"
  OTTERSCALE_SERVER_EXTERNAL_TUNNEL_URL: "https://{{ .Values.istio.externalIP }}:{{ .Values.otterscaleServer.nodePorts.tunnel }}"
  OTTERSCALE_SERVER_HARBOR_URL: {{ .Values.harbor.externalURL }}
  