kserve-llmisvc-resources:
  kserve:
    controller:
      llmisvc:
        enabled: true
    localmodel:
      enabled: true
    storage:
      uidModelcar: 2000

envoyProxy:
  # LoadBalancer / ClusterIP / NodePort
  type: NodePort

prometheus:
  serviceMonitor:
    enabled: true
