apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: kserve-envoyproxy
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        patch:
          value:
            spec:
              ports:
              - name: http-kserve
                nodePort: 32080
                port: 80
                protocol: TCP
                targetPort: 10080
        type: {{ .Values.envoyProxy.type }}
