apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: envoy-otterscale
  listeners:
    - name: http
      protocol: HTTP
      port: 32080
      allowedRoutes:
        namespaces:
          from: Same
