{{- $tls := .Values.listenerSet.tls }}
{{- if and $tls.enabled $tls.crt $tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llm-isvc-resources.tls.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-isvc-resources.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $tls.crt | b64enc }}
  tls.key: {{ $tls.key | b64enc }}
{{- end }}
