apiVersion: v2
name: otterscale-kubevirt
version: 0.1.0
# renovate: github=kubevirt/kubevirt
appVersion: "1.7.2"
description: >-
  KubeVirt — enables Kubernetes to manage VMs natively.
  Deploys CRDs, operator, and KubeVirt custom resource.
home: https://kubevirt.io
icon: https://github.com/kubevirt.png
sources:
  - https://github.com/otterscale/charts
maintainers:
  - name: Chung-Hsuan Tsai
    email: paul_tsai@phison.com
keywords:
  - kubevirt
  - virtualization
  - vm
type: application
kubeVersion: ">=1.25.0-0"
annotations:
  module.otterscale.io/depends-on: "otterscale-cdi"
  module.otterscale.io/namespace: "kubevirt"
  artifacthub.io/license: Apache-2.0
