apiVersion: v2
name: otterscale-gateway-api
version: 0.1.0
# renovate: github=kubernetes-sigs/gateway-api
appVersion: "1.4.1"
description: >-
  Kubernetes Gateway API — Standard channel CRDs
  (GatewayClass, Gateway, HTTPRoute, GRPCRoute, ReferenceGrant).
home: https://gateway-api.sigs.k8s.io
icon: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/refs/heads/main/site-src/images/logo/logo.svg
sources:
  - https://github.com/otterscale/charts
maintainers:
  - name: Chung-Hsuan Tsai
    email: paul_tsai@phison.com
keywords:
  - gateway-api
  - crds
  - networking
type: application
kubeVersion: ">=1.25.0-0"
annotations:
  module.otterscale.io/namespace: "default"
  artifacthub.io/license: Apache-2.0
