{{- if .Values.objectstoreService.enabled -}}
{{- $namespace := .Release.Namespace -}}
{{- $clusterName := (index .Values "rook-ceph-cluster").clusterName -}}
{{- range (index .Values "rook-ceph-cluster").cephObjectStores }}
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-{{ .name }}-external
  namespace: {{ $namespace }}
  labels:
    app: rook-ceph-rgw
    rook_object_store: {{ .name | quote }}
    rook_cluster: {{ $clusterName | quote }}
spec:
  ports:
    - name: rgw
      port: 80
      protocol: TCP
      targetPort: {{ .spec.gateway.port }}
      {{- if $.Values.objectstoreService.nodePort }}
      nodePort: {{ $.Values.objectstoreService.nodePort }}
      {{- end }}
  selector:
    app: rook-ceph-rgw
    rook_object_store: {{ .name | quote }}
    rook_cluster: {{ $clusterName | quote }}
  sessionAffinity: None
  type: NodePort
---
{{- end }}
{{- end }}
