{{- if .Values.objectstoreService.enabled -}}
{{- $namespace := include "rook-ceph-cluster.namespace" . -}}
{{- $clusterName := (index .Values "rook-ceph-cluster").clusterName | required "rook-ceph-cluster.clusterName is required" -}}
{{- range (index .Values "rook-ceph-cluster").cephObjectStores }}
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-{{ .name }}-external
  namespace: {{ $namespace }}
  labels:
    app: rook-ceph-rgw
    rook_object_store: {{ .name | quote }}
    rook_cluster: {{ $clusterName | quote }}
spec:
  ports:
    - name: rgw
      port: 80
      protocol: TCP
      targetPort: {{ .spec.gateway.port | default 8080 }}
  selector:
    app: rook-ceph-rgw
    rook_object_store: {{ .name | quote }}
    rook_cluster: {{ $clusterName | quote }}
  sessionAffinity: None
  type: NodePort
---
{{- end }}
{{- end }}
