{{- if and .Values.istio.enabled .Values.istio.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "otterscale.fullname" . }}-gateway
  namespace: {{ include "otterscale.namespace" . }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
  {{- if and .Values.istio.gateway.hostname (ne .Values.istio.gateway.hostname "*") }}
    hostname: {{ .Values.istio.gateway.hostname | quote }}
  {{- end }}
  {{- if .Values.istio.tls.enabled }}
  - name: https
    port: 443
    protocol: HTTPS
  {{- if and .Values.istio.gateway.hostname (ne .Values.istio.gateway.hostname "*") }}
    hostname: {{ .Values.istio.gateway.hostname | quote }}
  {{- end }}
    tls:
      mode: Terminate
      certificateRefs:
      - name: {{ include "otterscale.tls.secretName" . }}
  {{- end }}
{{- end }}
