{{- if and .Values.istio.enabled .Values.istio.virtualService.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "otterscale.fullname" . }}
  namespace: istio-system
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
spec:
  hosts:
    {{- toYaml .Values.istio.gateway.hosts | nindent 4 }}
  gateways:
    - {{ include "otterscale.gatewayRef" . }}
  http:
    {{- if .Values.keycloakx.enabled }}
    - headers:
        request:
          set:
            X-Forwarded-Proto: {{ if .Values.istio.tls.enabled }}"https"{{ else }}"http"{{ end }}
      match:
      - uri:
          prefix: {{ .Values.keycloakx.http.relativePath }}
      route:
      - destination:
          host: {{ include "otterscale.keycloakx.serviceName" . }}.{{ include "otterscale.namespace" . }}.svc.cluster.local
          port:
            number: {{ .Values.keycloakx.service.port }}
    {{- end }}
    {{- if .Values.harbor.enabled }}
    # ---- Harbor routes ----
    - match:
      - uri:
          prefix: /harbor
      rewrite:
          uri: /
      route:
      - destination:
          host: {{ include "otterscale.harbor.serviceName" $ }}.{{ include "otterscale.namespace" . }}.svc.cluster.local
          port:
            number: {{ include "otterscale.harbor.servicePort" $ }}
    {{- end }}
    # ---- OtterScale routes ----
    - match:
      - uri:
          prefix: /api/
      rewrite:
          uri: /
      route:
      - destination:
          host: {{ include "otterscale.server.fullname" $ }}.{{ include "otterscale.namespace" . }}.svc.cluster.local
          port:
            number: {{ .Values.server.ports.http }}
    - match:
      - headers:
          upgrade:
            exact: websocket
        uri:
          prefix: /vnc/
      route:
      - destination:
          host: {{ include "otterscale.server.fullname" $ }}.{{ include "otterscale.namespace" . }}.svc.cluster.local
          port:
            number: {{ .Values.server.ports.http }}
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: {{ include "otterscale.dashboard.fullname" $ }}.{{ include "otterscale.namespace" . }}.svc.cluster.local
          port:
            number: {{ .Values.dashboard.ports.http }}
{{- end }}
