hami:
  global:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "31992"

  scheduler:
    # binpack (concentrated) and spread
    defaultSchedulerPolicy:
      nodeSchedulerPolicy: binpack
      gpuSchedulerPolicy: binpack
    service:
      type: ClusterIP

  devicePlugin:
    enabled: true
    gpuOperatorToolkitReady:
      enabled: true
      hostPath: "/run/nvidia/validations"
    deviceSplitCount: 10
    deviceMemoryScaling: 1
    deviceCoreScaling: 1
    service:
      type: ClusterIP
    runtimeClassName: "nvidia"
    nvidiaNodeSelector:
      gpu: null
      otterscale.io/gpu: "true"
  
  dra:
    enabled: false

  hami-dra:
    drivers:
      nvidia:
        enabled: true
        # If you are using gpu driver on host, you need to set this to false
        containerDriver: true

# ServiceMonitor configuration for Prometheus
serviceMonitor:
  enabled: true
  interval: 15s
  scrapeTimeout: 15s
  path: /metrics
