hami:
  global:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "31992"

  scheduler:
    service:
      type: ClusterIP

  devicePlugin:
    enabled: true
    gpuOperatorToolkitReady:
      enabled: true
      hostPath: "/run/nvidia/validations"
    deviceSplitCount: 10
    deviceMemoryScaling: 1
    deviceCoreScaling: 1
    service:
      type: ClusterIP
    runtimeClassName: "nvidia"
    nvidiaNodeSelector:
      gpu: null
      otterscale.io/gpu: on

# ServiceMonitor configuration for Prometheus
serviceMonitor:
  enabled: true
  interval: 15s
  scrapeTimeout: 15s
  path: /metrics
