{{- if and .Values.envoy.enabled .Values.envoy.tls.enabled (eq (.Values.envoy.tls.mode | default "existingSecret") "provided") }}
{{- $crt := .Values.envoy.tls.provided.crt | required "envoy.tls.provided.crt must be set when envoy.tls.mode is 'provided'" -}}
{{- $key := .Values.envoy.tls.provided.key | required "envoy.tls.provided.key must be set when envoy.tls.mode is 'provided'" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterscale.tls.secretName" . }}
  namespace: {{ include "otterscale.gateway.namespace" . }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $crt | b64enc }}
  tls.key: {{ $key | b64enc }}
{{- end }}
