{{- if and .Values.envoy.enabled .Values.envoy.tls.enabled .Values.envoy.tls.crt .Values.envoy.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterscale.tls.secretName" . }}
  namespace: {{ include "otterscale.gateway.namespace" . }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.envoy.tls.crt | b64enc }}
  tls.key: {{ .Values.envoy.tls.key | b64enc }}
{{- end }}
