{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: model-operator
    control-plane: controller-manager
  name: {{ .Values.namespace.name }}
{{- end }}
