apiVersion: v2
name: otterscale-kserve-base
version: 1.1.1
# renovate: helm=kserve registry=oci://ghcr.io/kserve/charts
appVersion: "v0.18.0"
description: >-
  KServe LLMInferenceService CRDs — Custom Resource Definitions for KServe LLM inference.
  Deploys CRDs only.
home: https://kserve.github.io/website
icon: https://github.com/kserve.png
sources:
  - https://github.com/otterscale/charts
maintainers:
  - name: Chung-Hsuan Tsai
    email: paul_tsai@phison.com
keywords:
  - kserve
  - llm
  - inference
  - llminferenceservice
type: application
kubeVersion: ">=1.32.0-0"
dependencies:
  - name: kserve-llmisvc-crd
    version: v0.18.0
    repository: oci://ghcr.io/kserve/charts
  - name: kserve-localmodel-crd
    version: v0.18.0
    repository: oci://ghcr.io/kserve/charts
annotations:
  module.otterscale.io/depends-on: "otterscale-envoy-gateway,otterscale-envoy-ai-gateway,otterscale-leader-worker-set"
  module.otterscale.io/namespace: "kserve"
  artifacthub.io/license: Apache-2.0
  helm.sh/resource-policy: keep
