{{- if .Values.keycloakx.enabled -}}
{{- $dashboardSecretName := printf "%s-keycloakx-dashboard-client-secret" (include "otterscale.fullname" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $dashboardSecretName }}
  namespace: {{ include "otterscale.namespace" . }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloakx
type: Opaque
stringData:
  client-secret: {{ include "otterscale.keycloakx.dashboardClientSecret" . | quote }}
{{- if .Values.harbor.enabled }}
---
{{- $harborSecretName := printf "%s-keycloakx-harbor-client-secret" (include "otterscale.fullname" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $harborSecretName }}
  namespace: {{ include "otterscale.namespace" . }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloakx
type: Opaque
stringData:
  client-secret: {{ include "otterscale.keycloakx.harborClientSecret" . | quote }}
{{- end }}
{{- end }}
