{{- if .Values.keycloakx.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-otterscale-realm
  namespace: {{ include "otterscale.namespace" . }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  otterscale-realm.json: |
    {
      "realm": "otterscale",
      "displayName": "OtterScale",
      "enabled": true,
      "registrationAllowed": true,
      "rememberMe": true,
      "resetPasswordAllowed": true,
      "revokeRefreshToken": true,
      "refreshTokenMaxReuse": 2,
      "loginTheme": "otterscale-theme",
      "clients": [
        {
          "enabled": true,
          "clientId": "{{ .Values.keycloakx.clients.dashboard.id }}",
          "clientAuthenticatorType": "client-secret",
          "secret": "{{ include "otterscale.keycloakx.dashboardClientSecret" . }}",
          "protocol": "openid-connect",
          "authorizationServicesEnabled": false,
          "directAccessGrantsEnabled": false,
          "publicClient": false,
          "serviceAccountsEnabled": true,
          "standardFlowEnabled": true,
          "frontchannelLogout": true,
          "redirectUris": [
            "{{ include "otterscale.externalURL" . }}/*"
          ],
          "webOrigins": [
            "{{ include "otterscale.externalURL" . }}"
          ],
          "attributes": {
            "frontchannel.logout.session.required": "true",
            "pkce.code.challenge.method": "S256",
            "post.logout.redirect.uris": "{{ include "otterscale.externalURL" . }}/*"
          },
          "protocolMappers": [
            {
              "name": "audience-mapper",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-mapper",
              "consentRequired": false,
              "config": {
                "included.client.audience": "{{ .Values.keycloakx.clients.dashboard.id }}",
                "id.token.claim": "false",
                "lightweight.claim": "false",
                "access.token.claim": "true",
                "introspection.token.claim": "true"
              }
            },
            {
              "name": "roles-mapper",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-client-role-mapper",
              "consentRequired": false,
              "config": {
                "introspection.token.claim": "true",
                "multivalued": "true",
                "userinfo.token.claim": "false",
                "id.token.claim": "true",
                "lightweight.claim": "false",
                "access.token.claim": "true",
                "claim.name": "resource_access.{{ .Values.keycloakx.clients.dashboard.id }}.roles",
                "jsonType.label": "String"
              }
            }
          ]
        }
        {{- if .Values.harbor.enabled }},
        {
          "enabled": true,
          "clientId": "{{ .Values.keycloakx.clients.harbor.id }}",
          "clientAuthenticatorType": "client-secret",
          "secret": "{{ include "otterscale.keycloakx.harborClientSecret" . }}",
          "protocol": "openid-connect",
          "authorizationServicesEnabled": false,
          "directAccessGrantsEnabled": false,
          "publicClient": false,
          "serviceAccountsEnabled": false,
          "standardFlowEnabled": true,
          "frontchannelLogout": true,
          "redirectUris": [
            "{{ include "otterscale.harbor.externalURL" . }}/*"
          ],
          "webOrigins": [
            "{{ include "otterscale.harbor.externalURL" . }}"
          ],
          "attributes": {
            "frontchannel.logout.session.required": "true",
            "post.logout.redirect.uris": "{{ include "otterscale.harbor.externalURL" . }}/*"
          },
          "protocolMappers": [
            {
              "name": "username-mapper",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-attribute-mapper",
              "consentRequired": false,
              "config": {
                "introspection.token.claim": "true",
                "userinfo.token.claim": "true",
                "user.attribute": "harbor_username",
                "id.token.claim": "true",
                "lightweight.claim": "true",
                "access.token.claim": "true",
                "claim.name": "preferred_username",
                "jsonType.label": "String"
              }
            },
            {
              "name": "groups-mapper",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-group-membership-mapper",
              "consentRequired": false,
              "config": {
                "full.path": "false",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "groups",
                "userinfo.token.claim": "true"
              }
            }
          ]
        }
        {{- end }}
      ],
      "roles": {
        "client": {
          "{{ .Values.keycloakx.clients.dashboard.id }}": [
            {
              "name": "admin",
              "composite": false,
              "clientRole": true,
              "attributes": {}
            }
          ]
        }
      },
      "users": [
        {
          "username": "admin",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "password",
              "temporary": true
            }
          ],
          "attributes": {
            "harbor_username": ["admin_sso"]
          },
          "clientRoles": {
            "{{ .Values.keycloakx.clients.dashboard.id }}": ["admin"]
          }
          {{- if .Values.harbor.enabled }},
          "groups": ["/{{ .Values.harbor.oidc.adminGroup }}"]
          {{- end }}
        }
      ],
      {{- if .Values.harbor.enabled }}
      "groups": [
        {
          "name": "{{ .Values.harbor.oidc.adminGroup }}",
          "path": "/{{ .Values.harbor.oidc.adminGroup }}"
        }
      ],
      {{- end }}
      "internationalizationEnabled": true,
      "supportedLocales": ["zh-TW", "en"],
      "defaultLocale": "en",
      "authenticationFlows": [
        {
          "alias": "two steps browser",
          "description": "Browser based authentication with two steps",
          "providerId": "basic-flow",
          "topLevel": true,
          "builtIn": false,
          "authenticationExecutions": [
            {
              "authenticator": "auth-cookie",
              "authenticatorFlow": false,
              "requirement": "ALTERNATIVE",
              "priority": 10,
              "userSetupAllowed": false
            },
            {
              "authenticator": "auth-spnego",
              "authenticatorFlow": false,
              "requirement": "DISABLED",
              "priority": 20,
              "userSetupAllowed": false
            },
            {
              "authenticator": "identity-provider-redirector",
              "authenticatorFlow": false,
              "requirement": "ALTERNATIVE",
              "priority": 25,
              "userSetupAllowed": false
            },
            {
              "authenticatorFlow": true,
              "requirement": "ALTERNATIVE",
              "priority": 26,
              "flowAlias": "two steps browser Organization",
              "userSetupAllowed": false
            },
            {
              "authenticatorFlow": true,
              "requirement": "ALTERNATIVE",
              "priority": 30,
              "flowAlias": "two steps browser forms",
              "userSetupAllowed": false
            }
          ]
        },
        {
          "alias": "two steps browser Browser - Conditional Organization",
          "description": "Flow to determine if the organization identity-first login is to be used",
          "providerId": "basic-flow",
          "topLevel": false,
          "builtIn": false,
          "authenticationExecutions": [
            {
              "authenticator": "conditional-user-configured",
              "authenticatorFlow": false,
              "requirement": "REQUIRED",
              "priority": 10,
              "userSetupAllowed": false
            },
            {
              "authenticator": "organization",
              "authenticatorFlow": false,
              "requirement": "ALTERNATIVE",
              "priority": 20,
              "userSetupAllowed": false
            }
          ]
        },
        {
          "alias": "two steps browser Organization",
          "providerId": "basic-flow",
          "topLevel": false,
          "builtIn": false,
          "authenticationExecutions": [
            {
              "authenticatorFlow": true,
              "requirement": "CONDITIONAL",
              "priority": 10,
              "flowAlias": "two steps browser Browser - Conditional Organization",
              "userSetupAllowed": false
            }
          ]
        },
        {
          "alias": "two steps browser forms",
          "description": "Username, password, otp and other auth forms.",
          "providerId": "basic-flow",
          "topLevel": false,
          "builtIn": false,
          "authenticationExecutions": [
            {
              "authenticator": "auth-username-form",
              "authenticatorFlow": false,
              "requirement": "REQUIRED",
              "priority": 10,
              "userSetupAllowed": false
            },
            {
              "authenticator": "auth-password-form",
              "authenticatorFlow": false,
              "requirement": "REQUIRED",
              "priority": 20,
              "userSetupAllowed": false
            }
          ]
        }
      ],
      "browserFlow": "two steps browser",
      "attributes": {
        "darkMode": "true"
      },
      "components": {
        "org.keycloak.userprofile.UserProfileProvider": [
          {
            "providerId": "declarative-user-profile",
            "subComponents": {},
            "config": {
              "kc.user.profile.config": [
                "{\"attributes\":[{\"name\":\"username\",\"displayName\":\"${username}\",\"validations\":{\"length\":{\"min\":3,\"max\":255},\"username-prohibited-characters\":{},\"up-username-not-idn-homograph\":{}},\"permissions\":{\"view\":[\"admin\",\"user\"],\"edit\":[\"admin\",\"user\"]},\"multivalued\":false},{\"name\":\"email\",\"displayName\":\"${email}\",\"validations\":{\"email\":{},\"length\":{\"max\":255}},\"required\":{\"roles\":[\"user\"]},\"permissions\":{\"view\":[\"admin\",\"user\"],\"edit\":[\"admin\",\"user\"]},\"multivalued\":false},{\"name\":\"firstName\",\"displayName\":\"${firstName}\",\"validations\":{\"length\":{\"max\":255},\"person-name-prohibited-characters\":{}},\"required\":{\"roles\":[\"user\"]},\"permissions\":{\"view\":[\"admin\",\"user\"],\"edit\":[\"admin\",\"user\"]},\"multivalued\":false},{\"name\":\"lastName\",\"displayName\":\"${lastName}\",\"validations\":{\"length\":{\"max\":255},\"person-name-prohibited-characters\":{}},\"required\":{\"roles\":[\"user\"]},\"permissions\":{\"view\":[\"admin\",\"user\"],\"edit\":[\"admin\",\"user\"]},\"multivalued\":false},{\"name\":\"harbor_username\",\"displayName\":\"${profile.attributes.harbor_username}\",\"validations\":{},\"annotations\":{},\"permissions\":{\"view\":[\"admin\"],\"edit\":[\"admin\"]},\"multivalued\":false}],\"groups\":[{\"name\":\"user-metadata\",\"displayHeader\":\"User metadata\",\"displayDescription\":\"Attributes, which refer to user metadata\"}]}"
              ]
            }
          }
        ]
      }
    }

{{- end }}
