apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceServiceConfig
metadata:
  name: opt-125m
  namespace: {{ .Release.Namespace }}
spec:
  model:
    name: facebook/opt-125m
    uri: hf://facebook/opt-125m
  parallelism:
    tensor: 1
  router:
    gateway: {}
    route: {}
    scheduler: {}
  template:
    containers:
      - args:
          - --max-model-len
          - "512"
          - --gpu-memory-utilization
          - "0.8"
          - --tensor-parallel-size
          - "1"
          - --max-num-batched-tokens
          - "128"
        env:
          - name: LIBRARY_PATH
            value: /usr/lib/x86_64-linux-gnu:/usr/lib64
        image: ghcr.io/llm-d/llm-d-cuda:v0.6.0
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 30
        name: main
        resources:
          limits:
            cpu: "1"
            memory: 10Gi
            nvidia.com/gpu: "1"
            nvidia.com/gpumem: "8000"
          requests:
            cpu: "1"
            memory: 10Gi
            nvidia.com/gpu: "1"
            nvidia.com/gpumem: "8000"
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
    volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 2Gi
        name: dshm
