apiVersion: v2
name: otterscale-containerized-data-importer-base
version: 1.0.1
# renovate: github=kubevirt/containerized-data-importer
appVersion: "1.64.0"
description: >-
  CDI CRDs — Custom Resource Definitions for Containerized Data Importer.
  Deploys namespace and CRDs only.
home: https://github.com/kubevirt/containerized-data-importer
icon: https://github.com/kubevirt.png
sources:
  - https://github.com/otterscale/charts
maintainers:
  - name: Chung-Hsuan Tsai
    email: paul_tsai@phison.com
keywords:
  - cdi
  - kubevirt
  - storage
  - pvc
type: application
kubeVersion: ">=1.25.0-0"
annotations:
  module.otterscale.io/namespace: "cdi"
  artifacthub.io/license: Apache-2.0
  helm.sh/resource-policy: keep
