{{- if and .Values.harbor.enabled .Values.keycloakx.enabled .Values.harbor.oidc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.harbor.oidc.configSecretName | default "otterscale-harbor-oidc-config" }}
  namespace: {{ include "otterscale.namespace" . }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: harbor
type: Opaque
stringData:
  CONFIG_OVERWRITE_JSON: |
    {
      "auth_mode": "oidc_auth",
      "oidc_name": "Keycloak",
      "oidc_endpoint": "{{ include "otterscale.keycloakx.realmURL" . }}",
      "oidc_client_id": "{{ .Values.keycloakx.clients.harbor.id }}",
      "oidc_client_secret": "{{ include "otterscale.keycloakx.harborClientSecret" . }}",
      "oidc_scope": "{{ .Values.harbor.oidc.scope }}",
      "oidc_auto_onboard": {{ .Values.harbor.oidc.autoOnboard }},
      "oidc_groups_claim": "{{ .Values.harbor.oidc.groupsClaim }}",
      "oidc_admin_group": "{{ .Values.harbor.oidc.adminGroup }}",
      "oidc_verify_cert": false,
      "oidc_logout": false,
      "oidc_user_claim": "sub",
      "primary_auth_mode": true
    }
{{- end }}
