apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: otterscale-envoyproxy
  namespace: {{ .Release.Namespace }}
spec:
  logging:
    level:
      default: warn
  mergeGateways: true
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: NodePort
        patch:
          type: StrategicMerge
          value:
            spec:
              ports:
                - name: http-otterscale
                  port: 80
                  protocol: TCP
                  targetPort: 10080
                  nodePort: 30080
                - name: http-rook-ceph
                  port: 8301
                  protocol: TCP
                  targetPort: 8301
                  nodePort: 31080
