rook-ceph:
  rbacAggregate:
    # -- If true, create a ClusterRole aggregated to [user facing roles](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles) for objectbucketclaims
    enableOBCs: true
  # -- Many OBC additional config fields may be risky for administrators to allow users control over.
  obcAllowAdditionalConfigFields: "maxObjects,maxSize,bucketMaxObjects,bucketMaxSize,bucketPolicy,bucketLifecycle,bucketOwner"
  # -- Enable monitoring with Prometheus and Grafana
  monitoring:
    enabled: true

ceph-csi-operator:
  operatorConfig:
    namespace: rook-ceph
    driverSpecDefaults:
      imageSet:
        name: rook-csi-operator-image-set-configmap
      nodePlugin:
        priorityClassName: system-node-critical
      controllerPlugin:
        priorityClassName: system-cluster-critical

  drivers:
    rbd:
      enabled: true
      name: rook-ceph.rbd.csi.ceph.com # csi-provisioner-name
    cephfs:
      enabled: true
      name: rook-ceph.cephfs.csi.ceph.com # csi-provisioner-name
    nfs:
      enabled: false
      name: rook-ceph.nfs.csi.ceph.com # csi-provisioner-name
    nvmeof:
      enabled: false
      name: rook-ceph.nvmeof.csi.ceph.com # csi-provisioner-name
