# Default values for otterscale-model-operator
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  create: true
  name: otterscale-system

controllerManager:
  replicas: 1
  image:
    repository: ghcr.io/otterscale/model-operator
    tag: v0.9.2
    pullPolicy: IfNotPresent
  
  args:
    - --metrics-bind-address=:8443
    - --leader-elect
    - --health-probe-bind-address=:8081
  
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8081
    initialDelaySeconds: 15
    periodSeconds: 20
  
  readinessProbe:
    httpGet:
      path: /readyz
      port: 8081
    initialDelaySeconds: 5
    periodSeconds: 10
  
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
  
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

serviceAccount:
  create: true
  name: model-operator-controller-manager

service:
  type: ClusterIP
  metricsPort: 8443
  healthPort: 8081
