apiVersion: v2
name: otterscale-kubevirt-base
version: 0.1.0
# renovate: github=kubevirt/kubevirt
appVersion: "1.8.1"
description: >-
  KubeVirt CRDs — Custom Resource Definitions for KubeVirt.
  Deploys namespace and CRDs only.
home: https://kubevirt.io
icon: https://github.com/kubevirt.png
sources:
  - https://github.com/otterscale/charts
maintainers:
  - name: Chung-Hsuan Tsai
    email: paul_tsai@phison.com
keywords:
  - kubevirt
  - virtualization
  - vm
type: application
kubeVersion: ">=1.25.0-0"
annotations:
  meta.helm.sh/release-name: "kubevirt-crd"
  artifacthub.io/license: Apache-2.0
  helm.sh/resource-policy: keep
