apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: rook-ceph-ingress-gateway
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: envoy
  listeners:
    - name: http-rook-ceph
      protocol: HTTP
      port: 83
      allowedRoutes:
        namespaces:
          from: All
