apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otterscale.server.fullname" . }}-config
  namespace: {{ include "otterscale.namespace" . }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  OTTERSCALE_SERVER_ADDRESS: "0.0.0.0:{{ .Values.server.ports.http }}"
  OTTERSCALE_SERVER_TUNNEL_ADDRESS: "0.0.0.0:{{ .Values.server.ports.tunnel }}"
  OTTERSCALE_SERVER_EXTERNAL_URL: {{ include "otterscale.server.externalURL" . | quote }}
  OTTERSCALE_SERVER_EXTERNAL_TUNNEL_URL: {{ include "otterscale.server.externalTunnelURL" . | quote }}
  OTTERSCALE_SERVER_ALLOWED_ORIGINS: {{ include "otterscale.externalURL" . | quote }}
  {{- if .Values.keycloakx.enabled }}
  OTTERSCALE_SERVER_KEYCLOAK_REALM_URL: {{ include "otterscale.keycloakx.realmURL" . | quote }}
  OTTERSCALE_SERVER_KEYCLOAK_CLIENT_ID: {{ .Values.keycloakx.clients.dashboard.id | quote }}
  {{- end }}
  {{- if .Values.harbor.enabled }}
  OTTERSCALE_SERVER_HARBOR_URL: {{ .Values.harbor.externalURL | quote }}
  {{- end }}
