apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otterscale.server.fullname" . }}
  namespace: {{ include "otterscale.namespace" . }}
  labels:
    {{- include "otterscale.server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.server.replicaCount }}
  {{- end }}
  {{- with .Values.server.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.server.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "otterscale.server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otterscale.server.selectorLabels" . | nindent 8 }}
        {{- if and .Values.istio.enabled .Values.istio.sidecarInjection.enabled }}
        sidecar.istio.io/inject: "true"
        {{- end }}
        {{- with .Values.server.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/server/configmap.yaml") . | sha256sum }}
        {{- with .Values.server.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "otterscale.server.serviceAccountName" . }}
      {{- with (concat (.Values.global.imagePullSecrets | default list) (.Values.server.imagePullSecrets | default list)) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.server.terminationGracePeriodSeconds }}
      {{- with .Values.server.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: otterscale-server
          image: {{ include "otterscale.image" (dict "imageRoot" .Values.server.image "global" .Values.global "chart" .Chart) | quote }}
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          {{- with .Values.server.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args: ["server"]
          ports:
            - name: http
              containerPort: {{ .Values.server.ports.http }}
              protocol: TCP
            - name: tunnel
              containerPort: {{ .Values.server.ports.tunnel }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "otterscale.server.fullname" . }}-config
            {{- with .Values.server.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.server.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.server.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.server.readinessProbe.tcpSocket.port }}
            initialDelaySeconds: {{ .Values.server.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.server.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.server.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.server.livenessProbe.tcpSocket.port }}
            initialDelaySeconds: {{ .Values.server.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.server.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.server.startupProbe.enabled }}
          startupProbe:
            tcpSocket:
              port: {{ .Values.server.startupProbe.tcpSocket.port }}
            initialDelaySeconds: {{ .Values.server.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.server.startupProbe.failureThreshold }}
          {{- end }}
          {{- with .Values.server.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            {{- with .Values.server.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.server.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- with .Values.server.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
