ceph-csi-drivers:
  operatorConfig:
    namespace: rook-ceph
    driverSpecDefaults:
      imageSet:
        name: rook-csi-operator-image-set-configmap
      nodePlugin:
        priorityClassName: system-node-critical
        enableSeLinuxHostMount: true
      controllerPlugin:
        priorityClassName: system-cluster-critical

  drivers:
    rbd:
      enabled: true
      name: rook-ceph.rbd.csi.ceph.com # csi-provisioner-name
    cephfs:
      enabled: true
      name: rook-ceph.cephfs.csi.ceph.com # csi-provisioner-name
    nfs:
      enabled: false
      name: rook-ceph.nfs.csi.ceph.com # csi-provisioner-name
    nvmeof:
      enabled: false
      name: rook-ceph.nvmeof.csi.ceph.com # csi-provisioner-name
